name: Lint, test and Deploy Project
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/setup-node@v4
        with:
          ref: main
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint
      - name: run test cases
        run: npm run test
      - name: build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project..."