name: Notify channels
on: 
  workflow_run:
    workflows: ["Lint, test and Deploy Project"]
    types:
      - completed
jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify MS Teams channel
        run: echo 'Notifying teams channel....'